"use client"

import Link from "next/link"
import { siteConfig } from "@/config"

import { Banner } from "@/components/banner"

export function TermsOfUse() {
  return (
    <div className="space-y-4 pb-2 md:space-y-6 lg:space-y-8">
      <Banner
        title="Terms of Use"
        description="These terms of use outline the rules and regulations for the use of our website."
      />
      <div className="mx-auto w-full max-w-7xl space-y-20">
        <div className="mx-4 flex-col space-y-12 xl:mx-0">
          <div className="w-full max-w-4xl space-y-4 md:space-y-6">
            <h1 className="text-xl font-bold md:text-2xl">Terms</h1>
            <p>
              {siteConfig.capitalizeName} is not responsible for images
              generated by users of the tool. Users are responsible for making
              sure that they have proper permission or license to use the
              content within the generated images.
            </p>
            <h1 className="text-xl font-bold md:text-2xl">Images</h1>
            <p>
              {siteConfig.capitalizeName} is not responsible for any images you
              convert to favicon format. You should only use images that you
              have permission or license to use.
            </p>
            <h1 className="text-xl font-bold md:text-2xl">Google Fonts</h1>
            <p>
              The fonts within the font selector are from the open source
              project{" "}
              <Link
                target="_blank"
                href="https://fonts.google.com"
                className="text-blue-400 hover:underline"
              >
                Google Fonts
              </Link>
              . Click{" "}
              <Link
                target="_blank"
                href="https://fonts.google.com/attribution"
                className="text-blue-400 hover:underline"
              >
                here
              </Link>{" "}
              for the full list of fonts and their respective licenses. You
              should review the license of the font you&apos;ve chosen before
              usage in your project.
            </p>
            <h1 className="text-xl font-bold md:text-2xl">Twemoji</h1>
            <p>
              The emoji graphics are from the open source project{" "}
              <Link
                target="_blank"
                href="https://twemoji.twitter.com"
                className="text-blue-400 hover:underline"
              >
                Twemoji
              </Link>
              . The graphics are copyright 2020 Twitter, Inc and other
              contributors. The graphics are licensed under{" "}
              <Link
                target="_blank"
                href="https://creativecommons.org/licenses/by/4.0"
                className="text-blue-400 hover:underline"
              >
                CC-BY 4.0
              </Link>
              . You should review the license before usage in your project.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
