import type { Metadata } from "next"
import { JetBrains_Mono } from "next/font/google"

import { cn } from "@/lib/utils"

import "@/styles/globals.css"

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("antialiased", jetbrainsMono.className)}>
        {children}
      </body>
    </html>
  )
}
